name: phytospatial_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - tqdm
  # Direct geospatial & data tools
  - geopandas
  - rasterio=1.4.3
  - pandas
  - numpy=2.2.6
  - matplotlib=3.10.8
  - shapely=2.1.2
  # Used for implementing the processing pipeline
  - pyarrow=22.0.0
  - scikit-learn
  - scipy